### ISSUE TITLE
booting-on-vmware container linux config example incorrect

### ISSUE THREAD

**Issue by sanseihappa** [coreos/docs#1004]
The container linux config example gives:

```
# This config is meant to be consumed by the config transpiler, which will
# generate the corresponding Ignition config. Do not pass this config directly
# to instances of Container Linux.

systemd:
  units:
    - name: etcd2.service
      enable: true

passwd:
  users:
    - name: core
      passwordHash: $6$5s2u6/jR$un0AvWnqilcgaNB3Mkxd5yYv6mTlWfOoCYHZmfi3LDKVltj.E8XNKEcwWm...
      sshAuthorizedKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGdByTgSVHq...
```

When it should be using `password_hash` and `ssh_authorized_keys`.
