### ISSUE TITLE
https://coreos.com/os/docs/latest/installing-to-disk.html#container-linux-configs

### ISSUE THREAD

**Issue by naisanza** [coreos/docs#1111]
The Container Linux config fails the [Ignition validation test](https://coreos.com/validate/)

```
# This config is meant to be consumed by the config transpiler, which will
# generate the corresponding Ignition config. Do not pass this config directly
# to instances of Container Linux.

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGdByTgSVHq.......
```
