### ISSUE TITLE
Container Linux: Provide default ignition disk layout

### ISSUE THREAD

**Issue by galexrt** [coreos/docs#1125]
To allow for adding custom partitions to the system disk it would be good to have the default disk/partition layout as an Container Linux Config and Ignition Config as an extendable example on the https://github.com/coreos/docs/blob/master/os/sdk-disk-partitions.md page.
Currently I can't just add a new partition to the system partition without having written down all default partitions.

**Comment by galexrt** [comment]
I have come up with something like this:
```
storage:
  disks:
    - device: "/dev/sda"
      wipe_table: true
      partitions:
        - label: "EFI-SYSTEM"
          number: 1
          size: "134217728B"
          start: 0
          typeguid_: "C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
        - label: "BIOS-BOOT"
          number: 2
          size: "2097152B"
          start: 0
          typeguid_: "21686148-6449-6E6F-744E-656564454649"
        - label: "USR-A"
          number: 3
          size: "1073741824B"
          start: 0
          typeguid_: "5dfbf5f4-2848-4bac-aa5e-0d9a20b745a6"
        - label: "USR-B"
          number: 4
          size: "1073741824B"
          start: 0
          typeguid_: "5dfbf5f4-2848-4bac-aa5e-0d9a20b745a6"
        - label: "OEM"
          number: 6
          size: "134217728B"
          start: 0
          typeguid_: "0fc63daf-8483-4772-8e79-3d69d8477de4"
        - label: "OEM-CONFIG"
          number: 7
          size: "67108864B"
          start: 0
          typeguid_: "c95dc21a-df0e-4340-8d7b-26cbfa9a03e0"
        - label: "ROOT"
          number: 9
          size: "80GiB"
          start: 0
          typeguid_: "0FC63DAF-8483-4772-8E79-3D69D8477DE4"
        - label: "data1"
          number: 10
          size: "0"
          typeguid_: "3884dd41-8582-4404-b9a8-e9b84f2df50e"
```
But this configuration is not working. The bootup fails with something like:
```
[FAILED] Failed to start Verity Setup for /dev/mapper/usr.
...
--has-offset=: invalid numeric value
```
From the config I posted above, I have a server with two 3TB disks. The first disk should contain the Container Linux with the ROOT partition (about 80GiB in this case) but also a separate "empty" partition with the rest of the space allocated to it. Second disk is used completely for in this case a storage application.

**Comment by bgilbert** [comment]
`typeguid_` should be `type_guid`; docs are now fixed (https://github.com/coreos/container-linux-config-transpiler/pull/101).

Our images have partitions aligned to 2 MB boundaries (see https://github.com/coreos/scripts/commit/7ba6381f381a0aeb09529b9f6fc6289b84f11f47) but Ignition aligns partitions to 1 MB, so the recreated partitions have different offsets than the existing ones.  In addition, there's no guarantee that that the partition offsets and sizes in our images will never change, so it's probably not a good idea to hardcode the current layout into your config.

You can achieve the same effect by setting `wipe_table` to false and specifying the additional partition at a sufficiently large offset into the disk:

```yaml
storage:
  disks:
    - device: "/dev/sda"
      partitions:
        - label: "data1"
          number: 10
          start: "85GiB"
```

Container Linux automatically resizes the root filesystem to fill available space, so the above config produces an 82.7 GiB rootfs.

We should probably document that trick explicitly.
