### ISSUE TITLE
cloud-config adding ssh authorized_keys - documentation?

### ISSUE THREAD

**Issue by naisanza** [coreos/docs#1156]
From the documentation on installing to disk: https://coreos.com/os/docs/latest/installing-to-disk.html

This doesn't work:
```yaml
#cloud-config
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGdByTgSVHq...
```
After digging around and finding this: https://coreos.com/os/docs/latest/cloud-config.html

This works:
```yaml
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGdByTgSVHq...
```
