### ISSUE TITLE
local CoreOS update server

### ISSUE THREAD

**Issue by sknohsalla** [coreos/docs#491]
Hi,

what's the current solution for a local CoreOS update server for machines with no www access ?
And how can I implement the repo/update URL in the cloudconfig ?

Sorry if I missed this part in your documentation, couldn't find anything.

Thanks in advance for your help!

Cheers, Sven.

**Comment by robszumski** [comment]
You can run CoreUpdate within your cluster and sync the update packages locally to it: https://coreos.com/products/coreupdate/

In your cloud-config you can specify which update server to use:

```
#cloud-config

coreos:
  update:
    group: alpha
    server: https://customer.update.core-os.net/v1/update/
```

More info: https://coreos.com/docs/coreupdate/coreos/coreupdate-configure-machines/
