### ISSUE TITLE
cannot deploy "Configuration for etcd Role"

### ISSUE THREAD

**Issue by rbucker** [coreos/docs#597]
The [documentation](https://coreos.com/os/docs/latest/cluster-architectures.html) provides an exmple that looks like this:

```
#cloud-config

coreos:
  etcd2:
    name: etcdserver
    initial-cluster: etcdserver=http://10.0.0.101:2380
    initial-advertise-peer-urls: http://10.0.0.101:2380
    advertise-client-urls: http://10.0.0.101:2379
```

When I tried to use this configuration at digital ocean I realized it was not going to work. You can see in the initial-cluster and other params that the IP address is provided. Since the machines do not have static IP addresses before that are started this config file will not work.

As I was writing this ISSUE it occurs to me (untested) that maybe the config files you presented might work if I used the `coreos-cloudinit` utility instead of the user-data file.

PS:  I had tried variations of $private???? and nothing seemed to work.  I've opened a related issue with digital ocean.
