### ISSUE TITLE
os doc is out of date.

### ISSUE THREAD

**Issue by xiang90** [coreos/docs#755]
https://coreos.com/os/docs/latest/cluster-discovery.html

The https://coreos.com/os/docs/latest/cluster-discovery.html#existing-clusters section is not correct for etcd2 cluster.

We should replace it with https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#do-not-use-public-discovery-service-for-runtime-reconfiguration

**Comment by robszumski** [comment]
dup of https://github.com/coreos/docs/issues/739

I do think there is value in explaining how the system works, so we should update the existing doc if it makes sense.

**Comment by xiang90** [comment]
@robszumski I agree. As I suggested, we probably should just replace that section with the new one I listed.

**Comment by rca** [comment]
I found this issue via [etcd #4568](https://github.com/coreos/etcd/issues/4568), and while updating the docs is a great idea, they still do not describe what Issue #4568 asks:  How does one add to the cluster when a discovery URL has been used?

I have the same question, and [asked it on the Google Group](https://groups.google.com/forum/#!topic/coreos-user/DTmUyBiqoO0).  Instructions on doing so would be great.

In my case, I have an existing 7-node EC2 cluster where all nodes were created using public discovery.  I want to replace one of the cluster members with one of the other 4 proxy nodes.  What is the process for this?  Given the process, I'd be more than happy to update the docs.

Thank you!

**Comment by joshix** [comment]
@rca In short, one should switch to static discovery and then promote a proxy. That procedure(s) for etcd on CoreOS is described in [etcd cluster reconfiguration](https://github.com/coreos/docs/blob/master/etcd/etcd-live-cluster-reconfiguration.md). Feedback and or PRs on that document as you apply it in your environment are also welcome.

If you've deployed on another OS, the same changes need to be made but without the cloud-config facility (and potentially adapted for your init system if you're not on planet systemd.)

Let me know if that is helpful or if you run into any problems.

**Comment by rca** [comment]
The doc you pointed me to is pretty much what I was looking for, thanks, @joshix!

I'm now stuck elsewhere, however.  Given the [runtime reconfiguration doc @xiang90 pasted](https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#do-not-use-public-discovery-service-for-runtime-reconfiguration), it sounds frowned upon to use the public discovery service to add machines to the _CoreOS cluster_ once the initial members are bootstrapped.  On AWS I've been adding systems to a cluster by cloning the initial machines, which contain the discovery URL.  That appears to be bad practice.

Using your docs as a starting point, I came up with this drop-in that added a _proxy node_ into the cluster:

```
[Service]
ExecStartPre=/usr/bin/rm -rf /var/lib/etcd2/member /var/lib/etcd2/proxy
# here we clean previously defined ETCD_DISCOVERY environment variable, we don't need it as we've already bootstrapped etcd cluster and ETCD_DISCOVERY conflicts with ETCD_INITIAL_CLUSTER environment variable
Environment="ETCD_DISCOVERY="
# This is simply a proxy node
Environment="ETCD_PROXY=on"
# Paste this in from the `etcdctl member add` command
Environment="ETCD_NAME=64da18652980459485f293163be48130"
Environment="ETCD_INITIAL_CLUSTER=9f5c0c73117346169d791ce42a0fac68=http://172.30.0.124:2380,671d0f714275498e92e8167eaeecec48=http://172.30.0.123:2380,57a063c6f257472e9c7151fe120c116d=http://172.30.0.125:2380"
Environment="ETCD_INITIAL_CLUSTER_STATE=existing"
```

The additional line to make this work is `Environment="ETCD_PROXY=on"`.  To get the `ETCD_INITIAL_CLUSTER` setting I hacked it by running the following commands:

```
etcdctl member add junk http://junk:2380
# get the member ID from output
etcdctl member remove <ID from output>
# copy the environment output and remove the junk entry from `ETCD_INITIAL_CLUSTER`
```

Ideally there would be a command such as `etcdctl member env` that spat out the environment lines that `etcdctl member add` prints.

Finally, this translates to the following cloud-config (Note: tested as EC2 user data):

```yaml
#cloud-config

coreos:
  etcd2:
    proxy: on
    initial-cluster: 9f5c0c73117346169d791ce42a0fac68=http://172.30.0.124:2380,671d0f714275498e92e8167eaeecec48=http://172.30.0.123:2380,57a063c6f257472e9c7151fe120c116d=http://172.30.0.125:2380
    initial-cluster-state: existing
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
```
