### ISSUE TITLE
$prviate_ipv4 vartiable is empty - vmware guestinfo 

### ISSUE THREAD

**Issue by samiqs** [coreos/docs#868]
**$private_ipv4 token is replaced by an empty value.** 

```bash
core@master1 ~ $ etcdctl cluster-health
member a8459349e7362457 is healthy: got healthy result from http://:2379
cluster is healthy
core@master1 ~ $ cat /run/systemd/system/etcd2.service.d/20-cloudinit.conf 
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://:2379,http://:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/<token here>"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://:2380"
```

**Using guestinfo interface and editing the .vmx manually prior to booting vm:**

```bash
guestinfo.hostname = "master1"                                                  
guestinfo.interface.0.name = "ens192"                                           
guestinfo.interface.0.role = "private"                                          
guestinfo.coreos.config.data = "H4sICIz...."
guestinfo.coreos.config.data.encoding = "gzip+base64"
```

**Cloud Config:**

```yaml

#cloud-config

users:
  - name: "core"
    passwd: "$6$ro..."
    groups:
      - "sudo"
      - "docker"
    ssh-authorized-keys:
      - "ssh-rsa ..."

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/<token>
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
        ExecStart=/usr/share/oem/bin/vmtoolsd
        TimeoutStopSec=5

    - name: oem-cloudinit.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        Description=Cloudinit from VMware Backdoor

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/coreos-cloudinit --oem=vmware

  oem:
    bug-report-url: "https://github.com/coreos/bugs/issues"
    id: vmware
    name: VMWare
    version-id: "9.10.0-r3"
```

I am using the latest coreos image. Nothing in any of the logs I have looked at indicate any issue pertaining to why the variable is missing. I am not sure how to debug this. Any help would be appreciated.
