### ISSUE TITLE
Quay Enterprise on > Tectonic v1.4.5 

### ISSUE THREAD

**Issue by alekssaul** [coreos/docs#948]
Issue: When Quay Enterprise is deployed on Kubernetes, Quay is smart enough to detect the platform it's running on. On Kubernetes, Quay configuration is written to a secret object rather than a config.yaml file in the filesystem. With Tectonic v1.4.5 we have RBAC enabled in the Kubernetes API server and by default the serviceaccount for the namespace does not have access to update the Kubernetes Secret object. Quay being denied access to modify the secret causes failures within Quay to save it's configuration.

Proposed Solution: Create Role and RoleBindings for quay-enterprise namespace service account and grant it access to modify secret objects (quay-enterprise-config-secret ). Update the documentation to create these objects prior to Quay enterprise deployment. 

quay-servicetoken-role.yaml
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: quay-enterprise
  name: quay-enterprise-serviceaccount
rules:
  - apiGroups: [""] # The API group "" indicates the core API Group.
    resources: ["secrets"]
    verbs: ["get", "put", "patch", "update"]
    nonResourceURLs: []
```
quay-servicetoken-role-binding.yaml
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: quay-enterprise-secret-writer
  namespace: quay-enterprise
subjects:
  - kind: ServiceAccount 
    name: default
roleRef:
  kind: Role
  namespace: quay-enterprise
  name: quay-enterprise-serviceaccount
  apiVersion: rbac.authorization.k8s.io/v1alpha1
```

I've tested the Role-RoleBinding above and seem to resolve the issue. I am hoping @ericchiang can take a look at this to make sure it's acceptable before I submit a PR. Role grants access to modify all secrets under "quay-enterprise" namespace, in reality we only need to modify quay-enterprise-config-secret object. I've also followed a naming convention that made sense to me, please provide feedback.

/cc: @josephschorr , @kbrwn as we talked about this.

**Comment by ericchiang** [comment]
This works for me.

**Comment by alekssaul** [comment]
customer had to add the get verb for namespace to the Role
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: quay-enterprise
  name: quay-enterprise-serviceaccount
rules:
  - apiGroups: [""] # The API group "" indicates the core API Group.
    resources: ["secrets"]
    verbs: ["get", "put", "patch", "update"]
    nonResourceURLs: []
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
```
